#!/bin/bash
# ss-biomass-pfd API — VPS 部署（systemd + Nginx + 可选 certbot）
# 用法: sudo bash deploy/deploy.sh
# 要求: 在仓库根目录执行，或设置 SS_BIOMASS_ROOT=/opt/ss-biomass-pfd

set -euo pipefail

ROOT="${SS_BIOMASS_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
ENV_FILE="/etc/default/ss-biomass-api"
SERVICE_NAME="ss-biomass-api"
NGINX_CONF="/etc/nginx/conf.d/simapi.nice-ai.dev.conf"
DOMAIN="simapi.nice-ai.dev"
CERTBOT_EMAIL="${CERTBOT_EMAIL:-dachou5224@gmail.com}"

echo "==> ss-biomass-pfd API deploy @ ${ROOT}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "请使用 root 或 sudo 运行本脚本" >&2
  exit 1
fi

cd "${ROOT}"

if [[ ! -f requirements.txt ]]; then
  echo "错误: 未找到 ${ROOT}/requirements.txt" >&2
  exit 1
fi

echo "==> Python venv"
if [[ ! -d .venv ]]; then
  python3 -m venv .venv
fi
.venv/bin/pip install -q -U pip
.venv/bin/pip install -q -r requirements.txt

echo "==> 参考数据 data/reference"
if [[ ! -f "${ROOT}/data/reference/inci_streams.csv" ]]; then
  echo "    警告: 缺少 data/reference/inci_streams.csv，API 无法启动。" >&2
  echo "    请从开发机 rsync: rsync -avz ./data/reference/ nice-ai-LZ:${ROOT}/data/reference/" >&2
fi

echo "==> 环境变量 ${ENV_FILE}"
if [[ ! -f "${ENV_FILE}" ]]; then
  KEY="$(openssl rand -hex 32)"
  cat >"${ENV_FILE}" <<EOF
# Generated by deploy/deploy.sh — do not commit
SIM_API_KEY=${KEY}
SIM_API_ALLOWED_ORIGINS=https://nice-ai.dev,https://www.nice-ai.dev
EOF
  chmod 600 "${ENV_FILE}"
  echo "    已生成 SIM_API_KEY（保存在 ${ENV_FILE}）"
else
  echo "    保留现有 ${ENV_FILE}"
fi

echo "==> 目录权限 (www-data)"
if ! id www-data &>/dev/null; then
  echo "错误: 系统无 www-data 用户" >&2
  exit 1
fi
chown -R www-data:www-data "${ROOT}"

echo "==> systemd ${SERVICE_NAME}"
cp "${ROOT}/deploy/systemd/ss-biomass-api.service" "/etc/systemd/system/${SERVICE_NAME}.service"
systemctl daemon-reload
systemctl enable "${SERVICE_NAME}"
systemctl restart "${SERVICE_NAME}"
HEALTH_OK=0
for _ in $(seq 1 20); do
  if curl -sf "http://127.0.0.1:8765/health" >/dev/null; then
    HEALTH_OK=1
    break
  fi
  sleep 1
done
if [[ "${HEALTH_OK}" -ne 1 ]]; then
  echo "错误: 本地 health 检查失败" >&2
  journalctl -u "${SERVICE_NAME}" -n 30 --no-pager || true
  exit 1
fi
echo "    health OK (127.0.0.1:8765)"

echo "==> Nginx ${NGINX_CONF}"
if [[ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]]; then
  cp "${ROOT}/deploy/nginx-simapi.conf.example" "${NGINX_CONF}"
  echo "    使用 HTTPS 配置（证书已存在）"
else
  cp "${ROOT}/deploy/nginx-simapi-http.conf.example" "${NGINX_CONF}"
  echo "    使用 HTTP 引导配置（待 certbot 签发后切换 HTTPS）"
fi
nginx -t
systemctl reload nginx

echo "==> DNS 检查 ${DOMAIN}"
RESOLVED=""
if command -v dig &>/dev/null; then
  RESOLVED="$(dig +short "${DOMAIN}" A 2>/dev/null | head -1 || true)"
elif command -v getent &>/dev/null; then
  RESOLVED="$(getent ahostsv4 "${DOMAIN}" 2>/dev/null | awk '{print $1; exit}' || true)"
fi
if [[ -z "${RESOLVED}" ]]; then
  echo "    警告: 无法解析 ${DOMAIN}，跳过 certbot。请在 DNS 生效后执行:"
  echo "    certbot --nginx -d ${DOMAIN}"
else
  echo "    解析为 ${RESOLVED}"
  if command -v certbot &>/dev/null; then
    CB_EMAIL="${CERTBOT_EMAIL:-}"
    if [[ -z "${CB_EMAIL}" && -d /etc/letsencrypt/accounts ]]; then
      CB_EMAIL="$(grep -rho 'mailto:[^"]*' /etc/letsencrypt/accounts/*/regr.json 2>/dev/null | head -1 | sed 's/mailto://')"
    fi
    CERTBOT_ARGS=(--nginx -d "${DOMAIN}" --non-interactive --agree-tos)
    if [[ -n "${CB_EMAIL}" ]]; then
      CERTBOT_ARGS+=(-m "${CB_EMAIL}")
    else
      CERTBOT_ARGS+=(--register-unsafely-without-email)
    fi
    if certbot "${CERTBOT_ARGS[@]}"; then
      cp "${ROOT}/deploy/nginx-simapi.conf.example" "${NGINX_CONF}"
      nginx -t && systemctl reload nginx
      echo "    已切换 HTTPS 配置"
    elif [[ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]]; then
      echo "    certbot 跳过（证书已存在）"
      cp "${ROOT}/deploy/nginx-simapi.conf.example" "${NGINX_CONF}"
      nginx -t && systemctl reload nginx
    else
      echo "    certbot 失败，保持 HTTP 引导配置"
    fi
  else
    echo "    未安装 certbot"
  fi
fi

echo "==> 完成"
echo "    本地: curl -sS http://127.0.0.1:8765/health"
echo "    对外: curl -sS https://${DOMAIN}/health  (HTTPS 需 DNS + certbot)"
echo "    API Key: grep SIM_API_KEY ${ENV_FILE}"
